# Generated by Django 4.1 on 2025-01-27 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_anolectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.anolectivo')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.colegio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
