# Generated by Django 4.1 on 2025-02-01 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0003_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='ano_lectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.anolectivo'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.anolectivo')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.colegio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
