# Generated by Django 4.1 on 2025-02-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_colegio_ano_lectivo_curso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="colegio",
        ),
        migrations.AddField(
            model_name="curso",
            name="materia",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.materia",
            ),
            preserve_default=False,
        ),
    ]
