# Generated by Django 4.1 on 2025-02-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_remove_curso_colegio_curso_materia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={"ordering": ["ano"]},
        ),
    ]
