# Generated by Django 4.1 on 2025-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0006_alter_curso_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materia",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterField(
            model_name="materia",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
