# Generated by Django 4.1 on 2025-02-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0012_remove_parcial_materia_parcial_curso"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parcial",
            options={},
        ),
        migrations.AddField(
            model_name="nota",
            name="ano_lectivo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.anolectivo",
            ),
            preserve_default=False,
        ),
    ]
