# Generated by Django 4.1 on 2025-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0014_preguntaparcial_opcionpregunta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcial",
            name="tema",
            field=models.CharField(max_length=200),
        ),
    ]
