# Generated by Django 4.1 on 2025-02-07 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestion", "0015_alter_parcial_tema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "recordatorio",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutos antes"),
                            (30, "30 minutos antes"),
                            (60, "1 hora antes"),
                            (120, "2 horas antes"),
                            (1440, "1 día antes"),
                            (10080, "1 semana antes"),
                        ],
                        default=60,
                    ),
                ),
                ("recordatorio_enviado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ano_lectivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.anolectivo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora"],
            },
        ),
    ]
